version: '3.0'

services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql:5.6.23
    ports:
     - 3300:3306
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - env
volumes:
  db-data:
